# Generated by Django 4.1 on 2024-04-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_qr_data_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('sampled_by', models.CharField(max_length=250, verbose_name='Sampled by')),
                ('unit', models.CharField(max_length=250, verbose_name='Unit')),
                ('sample_point', models.CharField(max_length=250, verbose_name='Sample Point')),
                ('sample_type', models.CharField(max_length=250, verbose_name='Sample Type')),
                ('data_time', models.DateTimeField(verbose_name='Date Time')),
                ('hashing_name', models.CharField(max_length=250, verbose_name='Hash Name')),
            ],
        ),
    ]
